# Generated by Django 3.2.4 on 2021-06-25 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frutos', '0002_frequencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='celular',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='data_cadastro',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='observacao',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='pessoa',
            name='tipo',
            field=models.CharField(choices=[('M', 'Membro'), ('V', 'Visitante')], default='V', max_length=1),
        ),
    ]
